services:
  - type: web
    name: tap-and-table-jeopardy
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt --target ./libs
    startCommand: PYTHONPATH=libs python3 app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
