services:
  - type: web
    name: tap-and-table-jeopardy
    env: python
    region: ohio
    plan: free
    buildCommand: python3 -m pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
