services:
  - type: web
    name: tap-and-table-jeopardy
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
